"use client";
import { useState, type FormEvent } from "react";
import { CalendarDays, Clock3, UserRound, Phone, Check, X, Pencil, FileText, Printer, Bell, Languages, Settings, ChevronLeft, ChevronRight } from "lucide-react";
import { useMockup, type ModalState } from "./context";
import { appointmentError, clock, dentists, displayDate, minutes, type Appointment, type Locale } from "./data";
import type { Label } from "./labels";
import { Action, Alert, Avatar, Empty, Field, PatientIdentity, PickerInput, Status } from "./primitives";

export function MockupDialogs({ modal }: { modal: ModalState }) {
  const ctx = useMockup(); const { t, locale, patients, appointments, requests, notices, invoices, settings, openModal, closeModal, navigate, readNotice, updateStatus, rejectRequest, setLocale } = ctx;
  const id = "id" in modal ? modal.id : undefined;
  const appointment = appointments.find(a => a.id === id);
  const request = requests.find(r => r.id === id);
  if (modal.kind === "newAppointment" || modal.kind === "editAppointment") return <AppointmentForm appointment={appointment} />;
  if (modal.kind === "newPatient") return <PatientForm />;
  if (modal.kind === "appointment" && appointment) {
    const p = patients.find(p => p.id === appointment.patientId)!;
    return <><div className="mk-dialog-body"><div className="mk-detail-identity"><PatientIdentity patient={p} locale={locale} /><Status status={appointment.status} t={t} /></div><Alert patient={p} locale={locale} t={t} /><div className="mk-detail-grid"><div><span><CalendarDays />{t("date")}</span><strong>{displayDate(appointment.date, locale, true)}</strong></div><div><span><Clock3 />{t("time")}</span><strong><bdi>{clock(appointment.start)} – {clock(appointment.start + appointment.duration)}</bdi> · {appointment.duration} {t("minute")}</strong></div><div><span><UserRound />{t("dentist")}</span><strong>{dentists.find(d => d.id === appointment.dentistId)?.name[locale]}</strong></div><div><span><Phone />{t("phone")}</span><bdi>{p.phone}</bdi></div></div>{appointment.note && <div className="mk-note"><strong>{t("note")}</strong><p>{appointment.note}</p></div>}<Action onClick={() => navigate(`/mockup/patients/${p.id}`)}><FileText />{t("patientFile")}</Action></div><footer className="mk-dialog-footer">{appointment.status !== "cancelled" && appointment.status !== "completed" && <><Action variant="danger" onClick={() => openModal({ kind: "cancelAppointment", id: appointment.id })}>{t("cancelAppointment")}</Action><Action onClick={() => openModal({ kind: "editAppointment", id: appointment.id })}><Pencil />{t("edit")}</Action><Action variant="primary" onClick={() => updateStatus(appointment.id, appointment.status === "arrived" ? "completed" : "arrived")}><Check />{t(appointment.status === "arrived" ? "markCompleted" : "markArrived")}</Action></>}{(appointment.status === "cancelled" || appointment.status === "completed") && <Action onClick={closeModal}>{t("close")}</Action>}</footer></>;
  }
  if (modal.kind === "cancelAppointment" && appointment) return <><div className="mk-dialog-body"><p>{t("cancelWarning")}</p><PatientIdentity patient={patients.find(p => p.id === appointment.patientId)!} locale={locale} /><strong>{displayDate(appointment.date, locale)} · <bdi>{clock(appointment.start)}</bdi></strong></div><footer className="mk-dialog-footer"><Action onClick={() => openModal({ kind: "appointment", id: appointment.id })}>{t("back")}</Action><Action variant="danger" onClick={() => updateStatus(appointment.id, "cancelled")}>{t("confirmCancel")}</Action></footer></>;
  if (modal.kind === "request" && request) return <RequestReview requestId={request.id} />;
  if (modal.kind === "rejectRequest" && request) return <><div className="mk-dialog-body"><p>{t("rejectWarning")}</p><PatientIdentity patient={patients.find(p => p.id === request.patientId)!} locale={locale} /></div><footer className="mk-dialog-footer"><Action onClick={() => openModal({ kind: "request", id: request.id })}>{t("back")}</Action><Action variant="danger" onClick={() => rejectRequest(request.id)}>{t("confirmReject")}</Action></footer></>;
  if (modal.kind === "notifications") return <><div className="mk-notification-list">{notices.map(n => { const r = requests.find(r => r.id === n.requestId); const p = patients.find(p => p.id === r?.patientId); return r && p ? <button key={n.id} className={n.read ? "" : "mk-notice-unread"} onClick={() => { readNotice(n.id); openModal({ kind: "request", id: r.id }); }}><span className="mk-notice-icon"><Bell /></span><div><strong>{t("newRequestNotice")} {p.name[locale]}</strong><span>{displayDate(r.date, locale)} · <bdi>{clock(r.start)}</bdi></span><small>{t(n.read ? "read" : "unread")}</small></div>{!n.read && <span className="mk-dot mk-blue-dot" />}</button> : null; })}{!notices.length && <Empty text={t("noNotices")} />}</div><footer className="mk-dialog-footer"><Action onClick={() => navigate("/mockup/requests")}>{t("reviewRequests")}</Action></footer></>;
  if (modal.kind === "account") return <><div className="mk-dialog-body"><div className="mk-detail-identity"><Avatar name={locale === "ar" ? "سلمى أمين" : "Salma Amine"} large /><div><h3>{locale === "ar" ? "سلمى أمين" : "Salma Amine"}</h3><p className="mk-meta">{t("receptionist")}</p></div></div><Field label={t("language")}><div className="mk-input-icon"><Languages /><select value={locale} onChange={e => setLocale(e.target.value as Locale)}><option value="ar">العربية</option><option value="fr">Français</option></select></div></Field></div><footer className="mk-dialog-footer"><Action onClick={() => navigate("/mockup/settings")}><Settings />{t("settings")}</Action><Action onClick={closeModal}>{t("close")}</Action></footer></>;
  if (modal.kind === "invoice") {
    const invoice = invoices.find(i => i.id === id); if (!invoice) return <Empty text={t("empty")} />;
    const p = patients.find(p => p.id === invoice.patientId)!; const total = invoice.items.reduce((sum, item) => sum + item.amount, 0);
    const amount = (n: number) => new Intl.NumberFormat(locale === "ar" ? "ar-MA" : "fr-FR", { style: "currency", currency: "MAD" }).format(n);
    return <><div className="mk-document-stage"><article className="mk-print-document" dir={locale === "ar" ? "rtl" : "ltr"}><header><div><h2>{settings.name[locale]}</h2><p>{t("fictionalDocument")}</p></div><span className="mk-document-mark"><FileText /></span></header><div className="mk-invoice-heading"><h3>{t("invoice")}</h3><bdi>{invoice.id}</bdi></div><div className="mk-document-details"><div><span>{t("patient")}</span><strong>{p.name[locale]}</strong><bdi>{p.phone}</bdi></div><div><span>{t("date")}</span><strong>{displayDate(invoice.date, locale, true)}</strong><Status status={invoice.status} t={t} /></div></div><table className="mk-document-table"><thead><tr><th>{t("service")}</th><th>{t("amount")}</th></tr></thead><tbody>{invoice.items.map((item, index) => <tr key={index}><td>{item.name[locale]}</td><td><bdi>{amount(item.amount)}</bdi></td></tr>)}</tbody><tfoot><tr><th>{t("total")}</th><td><bdi>{amount(total)}</bdi></td></tr></tfoot></table><footer>{t("fictionalDocument")}</footer></article></div><footer className="mk-dialog-footer"><Action onClick={closeModal}>{t("close")}</Action><Action variant="primary" onClick={() => window.print()}><Printer />{t("print")}</Action></footer></>;
  }
  return <Empty text={t("empty")} />;
}

function AppointmentForm({ appointment, requestId }: { appointment?: Appointment; requestId?: string }) {
  const { t, locale, patients, appointments, requests, settings, date, dentist, saveAppointment, closeModal, openModal } = useMockup();
  const request = requests.find(r => r.id === requestId);
  const [draft, setDraft] = useState({ patientId: appointment?.patientId || request?.patientId || "", dentistId: appointment?.dentistId || request?.dentistId || (dentist === "all" ? "d1" : dentist), date: appointment?.date || request?.date || date, time: clock(appointment?.start ?? request?.start ?? 960), duration: String(appointment?.duration || 30), note: appointment?.note || "" });
  const [error, setError] = useState<Label | null>(null);
  const change = (key: keyof typeof draft, value: string) => { setDraft(current => ({ ...current, [key]: value })); setError(null); };
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (!draft.patientId || !draft.dentistId || !draft.date || !draft.time || !draft.duration) { setError("requiredError"); return; }
    const candidate: Appointment = { id: appointment?.id || `a-${crypto.randomUUID()}`, patientId: draft.patientId, dentistId: draft.dentistId, date: draft.date, start: minutes(draft.time), duration: Number(draft.duration), status: appointment?.status || "confirmed", note: draft.note.trim() };
    const problem = appointmentError(candidate, appointments, settings); if (problem) { setError(problem); return; } saveAppointment(candidate, requestId);
  };
  const p = patients.find(p => p.id === draft.patientId);
  return <form onSubmit={submit}><div className="mk-dialog-body">{requestId && <h3>{t("finalTime")}</h3>}<div className="mk-form-grid">{!requestId && <Field label={t("patient")} wide><div className="mk-input-icon"><UserRound /><select required disabled={!!requestId} value={draft.patientId} onChange={e => change("patientId", e.target.value)}><option value="">— {t("patient")} —</option>{patients.map(p => <option key={p.id} value={p.id}>{p.name[locale]} · {`\u2066${p.phone}\u2069`}</option>)}</select></div></Field>}{p && (!requestId || p.alert) && <div className="mk-field-wide"><Alert patient={p} locale={locale} t={t} /></div>}<Field label={t("dentist")}><div className="mk-input-icon"><UserRound /><select required value={draft.dentistId} onChange={e => change("dentistId", e.target.value)}>{dentists.map(d => <option key={d.id} value={d.id}>{d.name[locale]}</option>)}</select></div></Field><Field label={t("date")}><PickerInput type="date" label={t("date")} pickerLabel={t("openPicker")} required value={draft.date} onInput={e => change("date", e.currentTarget.value)} onChange={e => change("date", e.target.value)} /></Field><Field label={t("time")}><PickerInput type="time" label={t("time")} pickerLabel={t("openPicker")} required value={draft.time} onInput={e => change("time", e.currentTarget.value)} onChange={e => change("time", e.target.value)} /></Field><Field label={t("duration")}><div className="mk-input-icon"><Clock3 /><input type="number" required min="5" max="240" value={draft.duration} onChange={e => change("duration", e.target.value)} /></div></Field><Field label={`${t("note")} — ${t("optional")}`} wide><textarea className="mk-control" rows={2} maxLength={500} value={draft.note} onChange={e => change("note", e.target.value)} /></Field></div><p className="mk-meta">{t("workingHours")}: <bdi>{settings.open} – {settings.close}</bdi> · {settings.timezone}</p>{error && <p role="alert" className="mk-error">{t(error)}</p>}</div><footer className="mk-dialog-footer">{requestId && <Action variant="danger" className="mk-footer-start" onClick={() => openModal({ kind: "rejectRequest", id: requestId })}><X />{t("rejectRequest")}</Action>}<Action onClick={closeModal}>{t("cancel")}</Action><Action variant="primary" type="submit"><Check />{t(requestId ? "confirmRequest" : "save")}</Action></footer></form>;
}

function RequestReview({ requestId }: { requestId: string }) {
  const { t, locale, requests, patients, appointments, openModal } = useMockup();
  const r = requests.find(r => r.id === requestId)!; const p = patients.find(p => p.id === r.patientId)!; const committed = appointments.find(a => a.id === r.appointmentId);
  return <><div className="mk-dialog-body"><div className="mk-detail-identity"><PatientIdentity patient={p} locale={locale} /><Status status={r.status} t={t} /></div><div className="mk-detail-grid"><div><span>{t("patientPhone")}</span><bdi>{p.phone}</bdi></div><div><span>{t("senderPhone")}</span><bdi>{r.senderPhone}</bdi></div><div><span>{t("requestedTime")}</span><strong>{displayDate(r.date, locale)} · <bdi>{clock(r.start)}</bdi></strong></div><div><span>{t("requestId")}</span><bdi>{r.id}</bdi></div></div>{r.status !== "pending" && <><h3>{t("delivery")}</h3><div className="mk-delivery-list">{(r.senderPhone === p.phone ? [p.phone] : [p.phone, r.senderPhone]).map((phone, i) => <div key={phone}><bdi>{phone}</bdi><span><Check />{t(r.delivery?.[i] || "notSent")}</span></div>)}</div><p className="mk-meta">{t("deliveryHint")}</p>{committed && <div className="mk-committed"><CalendarDays /><div><span>{t("finalTime")}</span><strong>{displayDate(committed.date, locale)} · <bdi>{clock(committed.start)} – {clock(committed.start + committed.duration)}</bdi></strong><Status status={committed.status} t={t} /></div></div>}</>}</div>{r.status === "pending" ? <AppointmentForm requestId={r.id} /> : <footer className="mk-dialog-footer"><Action onClick={() => openModal({ kind: "notifications" })}>{locale === "ar" ? <ChevronRight /> : <ChevronLeft />}{t("notifications")}</Action></footer>}</>;
}

function PatientForm() {
  const { t, patients, addPatient, closeModal, navigate } = useMockup();
  const [draft, setDraft] = useState({ name: "", phone: "", age: "", alert: "" }); const [error, setError] = useState<Label | null>(null); const [duplicate, setDuplicate] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); const phone = draft.phone.replace(/[\s()-]/g, ""); if (!draft.name.trim()) { setError("requiredError"); return; } if (!/^\+[1-9]\d{7,14}$/.test(phone)) { setError("phoneError"); return; } const found = patients.find(p => p.phone === phone); if (found) { setError("duplicatePhone"); setDuplicate(found.id); return; } addPatient({ id: `P-${crypto.randomUUID().slice(0, 8)}`, name: { ar: draft.name.trim(), fr: draft.name.trim() }, phone, age: Number(draft.age), ...(draft.alert.trim() ? { alert: { ar: draft.alert.trim(), fr: draft.alert.trim() } } : {}) }); };
  const change = (key: keyof typeof draft, value: string) => { setDraft(current => ({ ...current, [key]: value })); setError(null); setDuplicate(""); };
  return <form onSubmit={submit}><div className="mk-dialog-body"><div className="mk-form-grid"><Field label={t("name")} wide><input className="mk-control" required maxLength={80} value={draft.name} onChange={e => change("name", e.target.value)} /></Field><Field label={t("phone")}><div className="mk-input-icon"><Phone /><input type="tel" dir="ltr" required placeholder="+212…" value={draft.phone} onChange={e => change("phone", e.target.value)} /></div></Field><Field label={t("age")}><input className="mk-control" type="number" min="0" max="120" required value={draft.age} onChange={e => change("age", e.target.value)} /></Field><Field label={`${t("medicalAlert")} — ${t("optional")}`} wide><textarea className="mk-control" rows={2} maxLength={300} value={draft.alert} onChange={e => change("alert", e.target.value)} /></Field></div>{error && <p role="alert" className="mk-error">{t(error)}</p>}{duplicate && <Action onClick={() => navigate(`/mockup/patients/${duplicate}`)}>{t("viewFile")}</Action>}</div><footer className="mk-dialog-footer"><Action onClick={closeModal}>{t("cancel")}</Action><Action variant="primary" type="submit">{t("save")}</Action></footer></form>;
}
