import type { Locale } from "./data";
const labels = {
  openPicker: ["فتح المنتقي", "Ouvrir le sélecteur"],
  schedule: ["جدول المواعيد", "Agenda"], patients: ["المرضى", "Patients"], requests: ["طلبات الحجز", "Demandes de rendez-vous"], billing: ["الفواتير والمستندات", "Factures et documents"], settings: ["الإعدادات", "Paramètres"],
  search: ["ابحث باسم المريض أو رقم الهاتف", "Rechercher un patient ou un téléphone"], notifications: ["الإشعارات", "Notifications"], account: ["الحساب", "Compte"], receptionist: ["حساب الاستقبال", "Compte réception"],
  today: ["اليوم", "Aujourd’hui"], next: ["اليوم التالي", "Jour suivant"], previous: ["اليوم السابق", "Jour précédent"], allDentists: ["جميع الأطباء", "Tous les dentistes"], dentist: ["الطبيب", "Dentiste"], newAppointment: ["موعد جديد", "Nouveau rendez-vous"],
  scheduleSubtitle: ["نظرة واضحة على يوم العيادة", "Une vue claire de la journée du cabinet"], todayAppointments: ["مواعيد اليوم", "Rendez-vous aujourd’hui"], pendingRequests: ["طلبات بانتظار المراجعة", "Demandes à examiner"], reviewRequests: ["مراجعة الطلبات", "Examiner les demandes"],
  appointments: ["المواعيد", "Rendez-vous"], time: ["الوقت", "Heure"], date: ["التاريخ", "Date"], duration: ["المدة بالدقائق", "Durée en minutes"], minute: ["دقيقة", "min"], timezone: ["التوقيت المحلي", "Fuseau horaire"],
  confirmed: ["مؤكد", "Confirmé"], arrived: ["حضر", "Arrivé"], completed: ["مكتمل", "Terminé"], cancelled: ["ملغى", "Annulé"], pending: ["بانتظار المراجعة", "À examiner"], rejected: ["مرفوض", "Refusé"], paid: ["مدفوعة", "Payée"], unpaid: ["غير مدفوعة", "Impayée"],
  close: ["إغلاق", "Fermer"], cancel: ["إلغاء", "Annuler"], save: ["حفظ", "Enregistrer"], edit: ["تعديل الموعد", "Modifier le rendez-vous"], cancelAppointment: ["إلغاء الموعد", "Annuler le rendez-vous"], confirmCancel: ["تأكيد إلغاء الموعد", "Confirmer l’annulation"],
  cancelWarning: ["سيُلغى هذا الموعد ويصبح الوقت متاحًا في الجدول.", "Ce rendez-vous sera annulé et le créneau sera libéré."], appointmentDetails: ["تفاصيل الموعد", "Détails du rendez-vous"], patient: ["المريض", "Patient"], phone: ["رقم الهاتف", "Téléphone"], medicalAlert: ["تنبيه طبي", "Alerte médicale"], noAlerts: ["لا توجد تنبيهات طبية مسجلة", "Aucune alerte médicale enregistrée"],
  patientFile: ["فتح ملف المريض", "Ouvrir le dossier patient"], note: ["ملاحظة", "Note"], optional: ["اختياري", "Facultatif"], newPatient: ["مريض جديد", "Nouveau patient"], name: ["اسم المريض", "Nom du patient"], arabicName: ["الاسم بالعربية", "Nom en arabe"], frenchName: ["الاسم بالفرنسية", "Nom en français"], age: ["العمر", "Âge"], years: ["سنة", "ans"],
  patientsSubtitle: ["الهوية والمواعيد والتنبيهات، في مكان واحد", "Identité, rendez-vous et alertes au même endroit"], viewFile: ["عرض الملف", "Voir le dossier"], patientId: ["رقم الملف", "N° de dossier"], backPatients: ["العودة إلى المرضى", "Retour aux patients"], appointmentHistory: ["سجل المواعيد", "Historique des rendez-vous"], patientDetails: ["بيانات المريض", "Informations du patient"],
  empty: ["لا توجد نتائج لعرضها", "Aucun résultat à afficher"], noAppointments: ["لا توجد مواعيد لهذا اليوم", "Aucun rendez-vous ce jour"], noNotices: ["لا توجد إشعارات", "Aucune notification"],
  all: ["الكل", "Tous"], status: ["الحالة", "Statut"], requestsSubtitle: ["راجع الطلب، ثم ثبّت الوقت المناسب للمريض", "Examinez la demande, puis confirmez le créneau du patient"], review: ["مراجعة الطلب", "Examiner la demande"], requestReview: ["مراجعة طلب الحجز", "Examen de la demande"], requestId: ["رقم الطلب", "N° de demande"], patientPhone: ["رقم المريض", "Téléphone du patient"], senderPhone: ["رقم مقدم الطلب", "Téléphone de l’expéditeur"], requestedTime: ["الوقت المطلوب — مبدئي", "Créneau demandé — provisoire"], finalTime: ["الموعد النهائي", "Rendez-vous définitif"], confirmRequest: ["تثبيت الموعد", "Confirmer le rendez-vous"], rejectRequest: ["رفض الطلب", "Refuser la demande"], confirmReject: ["تأكيد رفض الطلب", "Confirmer le refus"], rejectWarning: ["سيُغلق الطلب دون إنشاء موعد.", "La demande sera clôturée sans créer de rendez-vous."],
  delivery: ["حالة إبلاغ القرار", "Transmission de la décision"], delivered: ["تم التسليم — محاكاة", "Livré — simulation"], failed: ["فشل التسليم — محاكاة", "Échec de livraison — simulation"], notSent: ["لم يُبلّغ القرار بعد", "Décision pas encore transmise"], deliveryHint: ["حالة الإبلاغ مستقلة عن تثبيت الموعد. إذا تطابق الرقمان يُعرض مستلم واحد.", "La transmission est indépendante du rendez-vous. Un seul destinataire si les numéros sont identiques."],
  invoice: ["فاتورة", "Facture"], invoiceId: ["رقم الفاتورة", "N° de facture"], amount: ["المبلغ", "Montant"], total: ["الإجمالي", "Total"], documentPreview: ["معاينة المستند", "Aperçu du document"], print: ["طباعة المستند", "Imprimer le document"], service: ["الخدمة", "Prestation"], billingSubtitle: ["فواتير المرضى ومعاينة المستندات", "Factures patients et aperçu des documents"], fictionalDocument: ["مستند تجريبي — بيانات وهمية", "Document de démonstration — données fictives"],
  settingsSubtitle: ["بيانات العيادة وتفضيلات الحساب", "Informations du cabinet et préférences du compte"], clinicDetails: ["بيانات العيادة", "Informations du cabinet"], clinicNameAr: ["اسم العيادة بالعربية", "Nom du cabinet en arabe"], clinicNameFr: ["اسم العيادة بالفرنسية", "Nom du cabinet en français"], workingHours: ["ساعات العمل", "Horaires d’ouverture"], opens: ["بداية الدوام", "Ouverture"], closes: ["نهاية الدوام", "Fermeture"], language: ["لغة الحساب", "Langue du compte"], saveSettings: ["حفظ الإعدادات", "Enregistrer les paramètres"], saved: ["تم الحفظ في هذه الجلسة", "Enregistré pour cette session"],
  mockup: ["نسخة تجريبية", "Maquette interactive"], sessionOnly: ["بيانات وهمية • تُعاد عند تحديث الصفحة", "Données fictives • réinitialisées au rechargement"], newRequestNotice: ["طلب حجز جديد من", "Nouvelle demande de"], unread: ["غير مقروء", "Non lu"], read: ["مقروء", "Lu"],
  overlap: ["هذا الوقت يتعارض مع موعد للطبيب أو للمريض. اختر وقتًا آخر.", "Ce créneau chevauche un rendez-vous du dentiste ou du patient. Choisissez un autre horaire."], hoursError: ["اختر مدة من 5 إلى 240 دقيقة وموعدًا ضمن ساعات العمل.", "Choisissez une durée de 5 à 240 minutes et un créneau dans les horaires d’ouverture."], requiredError: ["يرجى تعبئة الحقول المطلوبة بشكل صحيح.", "Veuillez remplir correctement les champs obligatoires."], duplicatePhone: ["يوجد مريض بهذا الرقم. راجع ملفه قبل إنشاء سجل جديد.", "Un patient possède déjà ce numéro. Consultez son dossier avant de créer une nouvelle fiche."], phoneError: ["أدخل رقمًا دوليًا يبدأ بـ + ويتبعه 8 إلى 15 رقمًا.", "Saisissez un numéro international : + suivi de 8 à 15 chiffres."], hoursSettingsError: ["يجب أن يكون وقت النهاية بعد وقت البداية.", "L’heure de fermeture doit être après l’ouverture."],
  created: ["تم إنشاء الموعد", "Rendez-vous créé"], updated: ["تم تعديل الموعد", "Rendez-vous modifié"], patientCreated: ["تم إنشاء ملف المريض", "Dossier patient créé"], requestConfirmed: ["تم تثبيت الموعد وإغلاق الطلب", "Rendez-vous confirmé et demande clôturée"], requestRejected: ["تم رفض الطلب", "Demande refusée"], appointmentCancelled: ["تم إلغاء الموعد", "Rendez-vous annulé"], markArrived: ["تسجيل الحضور", "Marquer comme arrivé"], markCompleted: ["إكمال الموعد", "Terminer le rendez-vous"],
  scheduleFor: ["جدول اليوم", "Agenda du jour"], results: ["ملفات المرضى", "Dossiers patients"], noPatient: ["لم يتم العثور على المريض", "Patient introuvable"], back: ["رجوع", "Retour"],
} as const;
export type Label = keyof typeof labels;
export type Translate = (key: Label) => string;
export function translator(locale: Locale): Translate { return key => labels[key][locale === "ar" ? 0 : 1]; }
