"use client";
import { useState, type FormEvent } from "react";
import { ArrowLeft, ArrowRight, ChevronLeft, ChevronRight, CalendarDays, Phone, UserRound, FileText, Check, Clock3, Languages, Building2 } from "lucide-react";
import { useMockup } from "./context";
import { clock, dentists, displayDate, type Locale } from "./data";
import { Action, Alert, Avatar, Empty, Field, Filter, PatientIdentity, PickerInput, SearchField, Status } from "./primitives";

export function PatientsPage({ patientId }: { patientId?: string }) {
  const { t, locale, patients, appointments, navigate, openModal } = useMockup();
  const [query, setQuery] = useState("");
  if (patientId) {
    const patient = patients.find(p => p.id === patientId);
    if (!patient) return <><Action onClick={() => navigate("/mockup/patients")}>{t("backPatients")}</Action><Empty text={t("noPatient")} /></>;
    const history = appointments.filter(a => a.patientId === patient.id).sort((a, b) => `${b.date}${clock(b.start)}`.localeCompare(`${a.date}${clock(a.start)}`));
    return <><Action variant="quiet" onClick={() => navigate("/mockup/patients")}>{locale === "ar" ? <ArrowRight /> : <ArrowLeft />}{t("backPatients")}</Action><section className="mk-panel mk-profile"><div className="mk-profile-heading"><Avatar name={patient.name[locale]} large /><div><h2>{patient.name[locale]}</h2><span className="mk-meta"><bdi>{patient.id}</bdi> · {patient.age} {t("years")}</span></div></div><Alert patient={patient} locale={locale} t={t} /><div className="mk-detail-grid"><div><span><Phone />{t("phone")}</span><bdi>{patient.phone}</bdi></div><div><span><UserRound />{t("patientId")}</span><bdi>{patient.id}</bdi></div></div></section><section className="mk-panel"><div className="mk-section-heading"><h2>{t("appointmentHistory")}</h2></div>{history.length ? <div className="mk-record-list">{history.map(a => <button key={a.id} onClick={() => openModal({ kind: "appointment", id: a.id })}><CalendarDays /><div><strong>{displayDate(a.date, locale)}</strong><span><bdi>{clock(a.start)}</bdi> · {dentists.find(d => d.id === a.dentistId)?.name[locale]}</span></div><Status status={a.status} t={t} />{locale === "ar" ? <ChevronLeft /> : <ChevronRight />}</button>)}</div> : <Empty text={t("empty")} />}</section></>;
  }
  const filtered = patients.filter(p => `${p.name.ar} ${p.name.fr} ${p.phone}`.toLowerCase().includes(query.toLowerCase().trim()));
  return <section className="mk-panel"><div className="mk-list-toolbar"><SearchField value={query} onChange={setQuery} t={t} /><span className="mk-meta">{filtered.length} {t("results")}</span></div><div className="mk-table-wrap"><table className="mk-table mk-patients-table"><thead><tr><th>{t("patient")}</th><th>{t("patientId")}</th><th>{t("medicalAlert")}</th><th aria-label={t("viewFile")} /></tr></thead><tbody>{filtered.map(p => <tr key={p.id}><td><PatientIdentity patient={p} locale={locale} /></td><td><bdi className="mk-meta">{p.id}</bdi></td><td>{p.alert ? <span className="mk-inline-alert">{p.alert[locale]}</span> : <span className="mk-meta">{t("noAlerts")}</span>}</td><td><Action variant="quiet" onClick={() => navigate(`/mockup/patients/${p.id}`)}>{t("viewFile")}{locale === "ar" ? <ChevronLeft /> : <ChevronRight />}</Action></td></tr>)}</tbody></table></div>{!filtered.length && <Empty text={t("empty")} />}</section>;
}

export function RequestsPage() {
  const { t, locale, requests, patients, openModal } = useMockup();
  const [filter, setFilter] = useState("pending");
  const filtered = requests.filter(r => filter === "all" || r.status === filter);
  return <section className="mk-panel"><div className="mk-list-toolbar"><Filter label={t("status")} value={filter} onChange={setFilter} options={["pending", "confirmed", "rejected", "all"].map(s => ({ value: s, label: t(s as "pending" | "confirmed" | "rejected" | "all") }))} /><span className="mk-meta">{filtered.length} {t("requests")}</span></div><div className="mk-request-list">{filtered.map(r => { const p = patients.find(p => p.id === r.patientId)!; return <article className="mk-request-row" key={r.id}><div className="mk-request-main"><PatientIdentity patient={p} locale={locale} /><Status status={r.status} t={t} /></div><div className="mk-request-data"><div><span>{t("requestedTime")}</span><strong>{displayDate(r.date, locale)} · <bdi>{clock(r.start)}</bdi></strong></div><div><span>{t("senderPhone")}</span><bdi>{r.senderPhone}</bdi></div><div><span>{t("dentist")}</span><strong>{dentists.find(d => d.id === r.dentistId)?.name[locale]}</strong></div><Action onClick={() => openModal({ kind: "request", id: r.id })}>{t("review")}{locale === "ar" ? <ChevronLeft /> : <ChevronRight />}</Action></div></article>; })}</div>{!filtered.length && <Empty text={t("empty")} />}</section>;
}

export function BillingPage() {
  const { t, locale, invoices, patients, openModal } = useMockup(); const [filter, setFilter] = useState("all");
  const amount = (n: number) => new Intl.NumberFormat(locale === "ar" ? "ar-MA" : "fr-FR", { style: "currency", currency: "MAD" }).format(n);
  const filtered = invoices.filter(i => filter === "all" || i.status === filter);
  return <section className="mk-panel"><div className="mk-list-toolbar"><Filter label={t("status")} value={filter} onChange={setFilter} options={["all", "paid", "unpaid"].map(s => ({ value: s, label: t(s as "all" | "paid" | "unpaid") }))} /><span className="mk-meta">{filtered.length} {t("billing")}</span></div><div className="mk-table-wrap"><table className="mk-table mk-billing-table"><thead><tr><th>{t("invoiceId")}</th><th>{t("patient")}</th><th>{t("date")}</th><th>{t("amount")}</th><th>{t("status")}</th><th aria-label={t("documentPreview")} /></tr></thead><tbody>{filtered.map(i => <tr key={i.id}><td><div className="mk-invoice-number"><FileText /><bdi>{i.id}</bdi></div></td><td>{patients.find(p => p.id === i.patientId)?.name[locale]}</td><td>{displayDate(i.date, locale)}</td><td><bdi>{amount(i.items.reduce((sum, item) => sum + item.amount, 0))}</bdi></td><td><Status status={i.status} t={t} /></td><td><Action variant="quiet" onClick={() => openModal({ kind: "invoice", id: i.id })}>{t("documentPreview")}</Action></td></tr>)}</tbody></table></div>{!filtered.length && <Empty text={t("empty")} />}</section>;
}

export function SettingsPage() {
  const { t, locale, settings, saveSettings } = useMockup();
  const [draft, setDraft] = useState(settings); const [draftLocale, setDraftLocale] = useState<Locale>(locale); const [error, setError] = useState(false); const [saved, setSaved] = useState(false);
  const changed = () => { setSaved(false); setError(false); };
  const changeHours = (key: "open" | "close", value: string) => { changed(); setDraft(current => ({ ...current, [key]: value })); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (draft.close <= draft.open) { setError(true); return; } saveSettings(draft, draftLocale); setSaved(true); };
  return <form className="mk-panel mk-settings" onSubmit={submit}><section><div className="mk-settings-heading"><Building2 /><div><h2>{t("clinicDetails")}</h2><p>{t("sessionOnly")}</p></div></div><div className="mk-form-grid"><Field label={t("clinicNameAr")}><input required maxLength={60} className="mk-control" dir="rtl" value={draft.name.ar} onChange={e => { changed(); setDraft({ ...draft, name: { ...draft.name, ar: e.target.value } }); }} /></Field><Field label={t("clinicNameFr")}><input required maxLength={60} className="mk-control" dir="ltr" value={draft.name.fr} onChange={e => { changed(); setDraft({ ...draft, name: { ...draft.name, fr: e.target.value } }); }} /></Field><Field label={t("timezone")}><select className="mk-control" dir="ltr" value={draft.timezone} onChange={e => { changed(); setDraft({ ...draft, timezone: e.target.value }); }}>{["Africa/Casablanca", "Africa/Algiers", "Africa/Tunis", "Asia/Riyadh", "Africa/Bamako"].map(z => <option key={z}>{z}</option>)}</select></Field></div></section><section><div className="mk-settings-heading"><Clock3 /><h2>{t("workingHours")}</h2></div><div className="mk-form-grid"><Field label={t("opens")}><PickerInput type="time" label={t("opens")} pickerLabel={t("openPicker")} required value={draft.open} onInput={e => changeHours("open", e.currentTarget.value)} onChange={e => changeHours("open", e.target.value)} /></Field><Field label={t("closes")}><PickerInput type="time" label={t("closes")} pickerLabel={t("openPicker")} required value={draft.close} onInput={e => changeHours("close", e.currentTarget.value)} onChange={e => changeHours("close", e.target.value)} /></Field></div>{error && <p role="alert" className="mk-error">{t("hoursSettingsError")}</p>}</section><section><div className="mk-settings-heading"><Languages /><h2>{t("language")}</h2></div><select className="mk-control mk-language-select" aria-label={t("language")} value={draftLocale} onChange={e => { changed(); setDraftLocale(e.target.value as Locale); }}><option value="ar">العربية</option><option value="fr">Français</option></select></section><footer className="mk-settings-footer">{saved && <span className="mk-saved"><Check />{t("saved")}</span>}<Action variant="primary" type="submit">{t("saveSettings")}</Action></footer></form>;
}
